# Generated by Django 6.0.7 on 2026-08-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, to='users.castmember'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='certification',
            field=models.CharField(default='U/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
