# Generated by Django 6.0.7 on 2026-08-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['seat_number']},
        ),
    ]
