# Generated by Django 6.1 on 2026-08-28 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_booking_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='users_booki_booking_fa8ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie'], name='users_booki_movie_i_1ac8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['schedule'], name='users_booki_schedul_f3559b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='users_payme_status_f6a2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='users_payme_created_288bc6_idx'),
        ),
    ]
