# Generated by Django 6.1 on 2026-08-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_booking_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
