# Generated by Django 6.1 on 2026-08-30 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_payment_is_refunded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='users_booki_user_id_499425_idx'),
        ),
    ]
