# Generated by Django 6.1 on 2026-09-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='showschedule',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
        ),
    ]
